/*
 * RA Service
 * The RAservice is responsible for handling the request for enrollment and authorization certificates 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.multicert.project.v2x.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Response
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-07T17:25:28.225+01:00")
public class Response {
  @JsonProperty("requestDestination")
  private String requestDestination = null;

  @JsonProperty("requestEncoded")
  private String requestEncoded = null;

  @JsonProperty("requestId")
  private Long requestId = null;

  @JsonProperty("requestOrigin")
  private String requestOrigin = null;

  @JsonProperty("requestType")
  private Boolean requestType = null;

  @JsonProperty("responseMessage")
  private String responseMessage = null;

  public Response requestDestination(String requestDestination) {
    this.requestDestination = requestDestination;
    return this;
  }

   /**
   * Get requestDestination
   * @return requestDestination
  **/
  @ApiModelProperty(value = "")
  public String getRequestDestination() {
    return requestDestination;
  }

  public void setRequestDestination(String requestDestination) {
    this.requestDestination = requestDestination;
  }

  public Response requestEncoded(String requestEncoded) {
    this.requestEncoded = requestEncoded;
    return this;
  }

   /**
   * Get requestEncoded
   * @return requestEncoded
  **/
  @ApiModelProperty(value = "")
  public String getRequestEncoded() {
    return requestEncoded;
  }

  public void setRequestEncoded(String requestEncoded) {
    this.requestEncoded = requestEncoded;
  }

  public Response requestId(Long requestId) {
    this.requestId = requestId;
    return this;
  }

   /**
   * Get requestId
   * @return requestId
  **/
  @ApiModelProperty(value = "")
  public Long getRequestId() {
    return requestId;
  }

  public void setRequestId(Long requestId) {
    this.requestId = requestId;
  }

  public Response requestOrigin(String requestOrigin) {
    this.requestOrigin = requestOrigin;
    return this;
  }

   /**
   * Get requestOrigin
   * @return requestOrigin
  **/
  @ApiModelProperty(value = "")
  public String getRequestOrigin() {
    return requestOrigin;
  }

  public void setRequestOrigin(String requestOrigin) {
    this.requestOrigin = requestOrigin;
  }

  public Response requestType(Boolean requestType) {
    this.requestType = requestType;
    return this;
  }

   /**
   * Get requestType
   * @return requestType
  **/
  @ApiModelProperty(value = "")
  public Boolean getRequestType() {
    return requestType;
  }

  public void setRequestType(Boolean requestType) {
    this.requestType = requestType;
  }

  public Response responseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
    return this;
  }

   /**
   * Get responseMessage
   * @return responseMessage
  **/
  @ApiModelProperty(value = "")
  public String getResponseMessage() {
    return responseMessage;
  }

  public void setResponseMessage(String responseMessage) {
    this.responseMessage = responseMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.requestDestination, response.requestDestination) &&
        Objects.equals(this.requestEncoded, response.requestEncoded) &&
        Objects.equals(this.requestId, response.requestId) &&
        Objects.equals(this.requestOrigin, response.requestOrigin) &&
        Objects.equals(this.requestType, response.requestType) &&
        Objects.equals(this.responseMessage, response.responseMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestDestination, requestEncoded, requestId, requestOrigin, requestType, responseMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    requestDestination: ").append(toIndentedString(requestDestination)).append("\n");
    sb.append("    requestEncoded: ").append(toIndentedString(requestEncoded)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    requestOrigin: ").append(toIndentedString(requestOrigin)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    responseMessage: ").append(toIndentedString(responseMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

